# SPDX-License-Identifier: MIT
"""Self-contained minimal SKP containers for Blender dispatch integration."""

from __future__ import annotations

import base64
import io
import struct
import zipfile


_LEGACY_V8_BASE64 = """
//7/DlMAawBlAHQAYwBoAFUAcAAgAE0AbwBkAGUAbAD//v8HewA4AC4AMAAuADEAfQAAAQIDBAUGBwgJCgsMDQ4P
//7/D2kAbgB0AGUAZwByAGEAdABpAG8AbgAuAHMAawBwAADxU2X//wAACwBDVmVyc2lvbk1hcP/+/xNDAEEAdAB0
AHIAaQBiAHUAdABlAEMAbwBuAHQAYQBpAG4AZQByAAAAAAD//v8PQwBBAHQAdAByAGkAYgB1AHQAZQBOAGEAbQBl
AGQAAQAAAP/+/wdDAEMAYQBtAGUAcgBhAAUAAAD//v8HQwBFAG4AdABpAHQAeQADAAAA//7/EkMAQwBvAG0AcABv
AG4AZQBuAHQAQgBlAGgAYQB2AGkAbwByAAUAAAD//v8KQwBDAG8AbQBwAG8AbgBlAG4AdAALAAAA//7/D0MARABy
AGEAdwBpAG4AZwBFAGwAZQBtAGUAbgB0AAkAAAD//v8QQwBNAGEAdABlAHIAaQBhAGwATQBhAG4AYQBnAGUAcgAE
AAAA//7/D0MARABlAGYAaQBuAGkAdABpAG8AbgBMAGkAcwB0AAAAAAD//v8RQwBSAGUAbgBkAGUAcgBpAG4AZwBP
AHAAdABpAG8AbgBzACQAAAD//v8LQwBTAGgAYQBkAG8AdwBJAG4AZgBvAAcAAAD//v8JQwBQAGEAZwBlAEwAaQBz
AHQAAQAAAP/+/wlDAFMAawBlAHQAYwBoAEMAUwAAAAAA//7/D0MARABpAG0AZQBuAHMAaQBvAG4AUwB0AHkAbABl
AAQAAAD//v8KQwBUAGUAeAB0AFMAdAB5AGwAZQAFAAAA//7/DEMARgBvAG4AdABNAGEAbgBhAGcAZQByAAAAAAD/
/v8QQwBTAGsAcABTAHQAeQBsAGUATQBhAG4AYQBnAGUAcgACAAAA//7/EUMAVwBhAHQAZQByAG0AYQByAGsATQBh
AG4AYQBnAGUAcgACAAAA//7/BkMATABhAHkAZQByAAIAAAD//v8NQwBMAGEAeQBlAHIATQBhAG4AYQBnAGUAcgAE
AAAA//7/CUMATQBhAHQAZQByAGkAYQBsAAwAAAD//v8FQwBFAGQAZwBlAAIAAAD//v8HQwBWAGUAcgB0AGUAeAAA
AAAA//7/DkMAUwBrAGUAdABjAGgAVQBwAE0AbwBkAGUAbAAWAAAA//7/EkUAbgBkAC0ATwBmAC0AVgBlAHIAcwBp
AG8AbgAtAE0AYQBwAAAAAAABAAAAsAQAAAAAAAAAAAEAAAAAAAAAAAAAAAAA//7/AAMAAAABAAAA//7/C1AAYQBn
AGUATwBwAHQAaQBvAG4AcwD//v8OUwBoAG8AdwBUAHIAYQBuAHMAaQB0AGkAbwBuAAcB//7/DlQAcgBhAG4AcwBp
AHQAaQBvAG4AVABpAG0AZQAGAAAAAAAA+D///v8A//8AABMAQ0F0dHJpYnV0ZUNvbnRhaW5lcgAA//8BAA8AQ0F0
dHJpYnV0ZU5hbWVkAAAAAAAA//7/D00AbwBkAGUAbABQAHIAbwBwAGUAcgB0AGkAZQBzAP/+/wxJAHMAQwBsAGEA
cwBzAGkAZgBpAGUAZAAHAP/+/wAAAAAAAAAAAP//BQAHAENDYW1lcmEAAAAAAAAkQAAAAAAAADRAAAAAAAAAPkAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAIBBQAAAAAAAgEZAAZqZ
mZmZmbk/AAAAAABAj0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAB//7/AAAAAAAAAABAAAAAAAAA
AAhAAAAAAAAAEEAAAAAAAAAUQAAAAgAAAAEAAQEAAAD/////gICA/wAAAP9AQED/AQABAAgAAAABAwAAAAAEAAAA
AQUAAAAABgAAAAEAAAAAAOHhyP+AgMj/AAAAAAAA6D8AAAAAAADgPwABAP8AAP8BAAAAAAAA0D8AAAAAAADAPzIA
AAACAAAAAQABAMDAwP//AAD/AP8A/wEBAAQAAAADAAAAAQAAAAIAAAABAAAAAgAAAAMAAAABH4XrUbge1T8AAQID
BAEfhetRuB7lPwEArkfhehSu7z8BMzMzMzMz8z8AAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA//8C
AAYAQ0xheWVyAAD//v8GTABhAHkAZQByADAAAAAA//7/DEwAYQB5AGUAcgBfAEwAYQB5AGUAcgAwAAAB/1RU///+
/wAAAAAAAAAAAAAAAAAAAOA/AAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAA8VNlAf/+/wNVAFMAQQD//v8MQgBvAHUA
bABkAGUAcgAgACgAQwBPACkAAAAAAAAAXsAAAAAAAIBGQAAAAAAAABzAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAA
AQABAFAAAAAUAAAAAQAAAAAAAAAAAAAAAAABAQAAAQAAAAAAAAAAJEAAAAAAAAAkQAAAAAAAACRAzTt/Zp6g5j/N
O39mnqDmPwAAAAAAAAAAzTt/Zp6g5r/NO39mnqDmPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAQAKAAAACwAAAAwAAAANAAAADgAAAAEKFB7/AAEAAAAAAAD0PwAAAAAAAAAEQCgyPP9GUFr/DwAAAAAAAAAC
AAAAAwAAAAEEAAAAAAoUHv8oMjz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQVJDSElWRQ==
"""


def legacy_v8_bytes() -> bytes:
    """Return a minimal valid pre-ZIP SketchUp 8 model."""
    return base64.b64decode(_LEGACY_V8_BASE64)


def modern_zip_bytes() -> bytes:
    """Return a minimal valid ZIP/TLV model with a modern raw header."""

    def record(tag: int, payload: bytes) -> bytes:
        return struct.pack("<HI", tag, len(payload)) + payload

    # The root locator requires a plausible top-level record of at least 100
    # bytes. The parser intentionally ignores this ID-counter payload.
    model_data = record(0x01F4, record(0x01F5, bytes(100)))
    archive = io.BytesIO()
    with zipfile.ZipFile(archive, "w") as zip_file:
        zip_file.writestr("model.dat", model_data)
    header = "SketchUp Model {26.0.0}\n".encode("utf-16le")
    return header + archive.getvalue()
